[package]
name = "resp_serde"
description = "REdis Serialization Protocol with serde"
version = "0.1.0"
authors = ["LOU Xun <aquarhead@ela.build>"]
edition = "2018"

[dependencies]
serde = "1.0"
thiserror = "1.0"

[dev-dependencies]
serde = {version = "1.0", features = ["derive"]}
